begin on support for Choice in Optuna parsing
automl/amltk pull request #290
Opened 2024-10-29 16:17 UTC by berombau

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Minimal Example / How should this PR be tested?

#### Any other comments?

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-29 19:10 UTC, eddiebergman requested changes

2024-10-29 19:10 UTC, eddiebergman commented on src/amltk/optimization/optimizers/optuna.py
> +                (not any(c in k for c in delete_other_options))
This line might need a second look, I had a bug a while back with something similar where essentially the `c` was present in some other `k` in another part of the pipeline that shouldn't have been effected by the given choice.

I'm on my phone so I cant write a concrete example but see the overall review comment for more

2024-10-29 19:16 UTC, eddiebergman commented
Looks really good, clean and well done, many thanks!

I would ask that the actual sampling function is factored into its own function that is then tested a bit more as to it's sampling behaviour.

This wasn't required for the other optimizers as I relied on them testing them own functionality, i.e. I dont want to test that other optimizers have their internals correct.

However here, since we are the ones implementing the sampling procedure, might be good to have it factored out and testable.

You can make it a private function of the module outside of the class as generally I don't think a user should be exposed to it.

For the actual study object, you can choose any sampler that makes sense to you!

Things to test are what was mentioned in the comment but also maybe that deeper more heirarchical pipelines work too. You can see this file and likely just copy and paste one of those, or however you see fit!

2024-10-30 16:15 UTC, eddiebergman commented
The random elements is usually just a thing of not giving a component a name. To do the configuring properly, I had to give them some identifier.

In any case, happy to push this through once the test pass. In any case, I can turn the remaining thing into an issue so this can be merged!

Very appreciative of your work!

2024-10-30 16:33 UTC, berombau commented
Thanks for the help! It's a really nice toolkit and codebase, was very glad when I found it 👍 

The mypy crashes on my pre-commit, so running it locally.
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 2

tests/scheduling/test_scheduler.py:116: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.8.0
```

2024-10-30 18:52 UTC, eddiebergman commented
> Thanks for the help! It's a really nice toolkit and codebase, was very glad when I found it 👍
> 
> The mypy crashes on my pre-commit, so running it locally.
> 
> ```
> mypy.....................................................................Failed
> - hook id: mypy
> - exit code: 2
> 
> tests/scheduling/test_scheduler.py:116: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
> https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
> Please report a bug at https://github.com/python/mypy/issues
> version: 1.8.0
> ```

Aye I'm aware of this issue, it's very annoying. I can't figure out what causes it but clearing cache seems to sometimes fix it -_-

2024-10-31 13:49 UTC, merged